apidoc:
  title: EFS SDK AccessManager-API
  oauth2:
    config-url: https://sdk-dev.efs.ai/auth/realms/efs-sdk/.well-known/openid-configuration
sas:
  token:
    expiration:
      read: 60
      write: 60
      delete: 60
    cache:
      buffer: 2
server:
  port: 8090
  servlet:
    context-path: /accessmanager
  error:
    include-message: always
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://sdk-dev.efs.ai/auth/realms/efs-sdk/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: sdk-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://sdk-dev.efs.ai/auth/realms/efs-sdk
            user-name-attribute: preferred_username
  kafka:
    admin:
      fail-fast: true
    bootstrap-servers: <EVENTHUB-NAMESPACE>.servicebus.windows.net:9093
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://<EVENTHUB-NAMESPACE>.servicebus.windows.net/;SharedAccessKeyName=<POLICY_NAME>;SharedAccessKey=<SHARED_ACCESS_KEY>";
      security:
        protocol: SASL_SSL
      group:
        id: $Default
accessmanager:
  topic:
    upload-complete: accessmanager-commit
  storage:
    user:
      client-id: <CLIENT-ID>
      client-secret: <CLIENT-SECRET>
      tenant: <TENANT>
    resourcegroup: SDK
  organizationmanager-endpoints:
    organization: http://localhost:8091/organizationmanager/api/v1.0/organization
    space: http://localhost:8091/organizationmanager/api/v1.0/space
management:
  endpoints:
    web:
      exposure:
        include: [
          prometheus,
          health,
          info
        ]