spring:
  config:
    import: "kubernetes:"
  application:
    name: accessmanager
  cloud:
    kubernetes:
      secrets:
        enabled: true
        paths:
          - /etc/secrets
          - /etc/storage-secret
      config:
        paths:
          - /etc/application/application.yml
          - /etc/application/applicationinsights.json
        enable-api: false
      reload:
        enabled: false
