apiVersion: v1
kind: ServiceAccount
metadata:
  name: accessmanager-account
  namespace: backend
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: accessmanager-namespace-reader-binding
  namespace: backend
subjects:
- kind: ServiceAccount
  name: accessmanager-account
  namespace: backend
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: ""
