apiVersion: v1
kind: Secret
stringData:
  accessmanager.storage.user.client-id: $(AZURE_STORAGE_CLIENT_ID)
  accessmanager.storage.user.client-secret: $(AZURE_STORAGE_CLIENT_SECRET)
  accessmanager.storage.user.tenant: $(AZURE_TENANT_ID)
metadata:
  name: accessmanager-secret
  namespace: backend
type: Opaque